message: "api-gateway-dev config file"

spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            # server:
            #     webflux:
            #         routes:
            #             - id: sale-service
            #               uri: http://localhost:8081
            #               predicates: 
            #                 - Path=/sales/**
            #               filters:
            #                 - StripPrefix=1

            #             - id: product-service
            #               uri: http://localhost:8082
            #               predicates:
            #                 - Path=/products/**
            #               filters:
            #                 - StripPrefix=1

            #             - id: customer-service
            #               uri: http://localhost:8083
            #               predicates:
            #                 - Path=/customers/**
            #               filters:
            #                 - StripPrefix=1
server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka