message: "products-ms-dev config file"

spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
            bindings:
                salesProductResponse-out-0:
                    destination: sales-products-response-events
                    group: sales-products-response-group
                    content-type: application/json
                salesProductRequest-in-0:
                    destination: sales-products-events
                    group: sales-products-service-group

server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
        prefer-ip-address: true