message: "sales-ms-dev config file"

spring:
    cloud:
        function:
            definition: salesCustomerResponse;salesProductResponse
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
            bindings:
                salesProductRequest-out-0:
                    destination: sales-products-events
                    content-type: application/json
                salesProductResponse-in-0:
                    destination: sales-products-response-events
                    group: sales-products-response-group
                salesCustomerRequest-out-0:
                    destination: sales-customers-events
                    content-type: application/json
                salesCustomerResponse-in-0:
                    destination: sales-customers-response-events
                    group: sales-customers-response-group
server:
    port: 8081

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true

management:
    tracing:
        sampling:
            probability: 1.0
    otlp:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans